# @package _global_

defaults:
  - data: default
  - model: random_forest
  - paths: default
  - hydra: default
  - _self_


# task name, determines output directory path
task_name: "train"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
tags: ["dev"]

mlflow:
  experiment_name: churn-classification
  run_name: ??