defaults:
  - data: default
  - mlflow: default
  - model: random_forest
  - paths: default
  - hydra: default

main:
  experiment_name: "mlchurn_classification"


# task name, determines output directory path
task_name: "train"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
tags: ["dev"]
